# Generated by Django 5.2 on 2025-04-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aicameradata_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='schedule',
        ),
    ]
