# Generated by Django 5.2 on 2025-04-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_group_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='student_count_today',
            field=models.IntegerField(default=0),
        ),
    ]
