# Generated by Django 5.2 on 2025-04-24 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_group_student_count_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_data', models.JSONField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.group')),
            ],
        ),
    ]
